"""
Smart Door Security System - Configuration Settings
"""

import os
from pathlib import Path

BASE_DIR      = Path(__file__).resolve().parent.parent
DATABASE_PATH = BASE_DIR / "database" / "smart_door.db"

CAMERA_INDEX          = 0
CAMERA_WIDTH          = 640
CAMERA_HEIGHT         = 480
CAMERA_FPS            = 30
CAMERA_BUFFER_SIZE    = 1
CAMERA_FRAME_TIMEOUT  = 5
CAMERA_RETRY_ATTEMPTS = 3

# SFace L2 threshold is ~1.128 (using 1.12 for slightly stricter matching)
FACE_RECOGNITION_TOLERANCE = 1.12
FACE_DETECTION_MODEL       = "hog"
FACE_ENCODING_JITTERS      = 1
# SFace cosine threshold is ~0.363 (using 0.36)
FACE_COSINE_THRESHOLD      = 0.36
FACE_CONSECUTIVE_FRAMES    = 5

SERVO_PWM_PIN          = 18
SERVO_PWM_FREQUENCY    = 50
SERVO_DUTY_MIN         = 2.5
SERVO_DUTY_MAX         = 12.5
SERVO_DUTY_CLOSED      = 7.5
SERVO_TRANSITION_DELAY = 0.5
SERVO_REVOLUTIONS_PER_SWEEP = 7
SERVO_FULL_REVOLUTION_DEG  = 360
SERVO_TOTAL_DEG_PER_SWEEP   = SERVO_REVOLUTIONS_PER_SWEEP * SERVO_FULL_REVOLUTION_DEG  # 2520
SERVO_440_DEG_DURATION      = 1.9
SERVO_2520_DEG_DURATION     = SERVO_440_DEG_DURATION * (SERVO_TOTAL_DEG_PER_SWEEP / 440)  # ≈10.882 s

SERVO_ANGLE_OPEN  = 90
SERVO_ANGLE_CLOSE = 0
SERVO_DIRECTION   = 1

ULTRASONIC_TRIG_PIN       = 23
ULTRASONIC_ECHO_PIN       = 24
ULTRASONIC_ONE_WAY_FACTOR = 0.01723
ULTRASONIC_TIMEOUT        = 0.050
ULTRASONIC_RETRIES        = 3
ULTRASONIC_RETRY_DELAY    = 0.050
ULTRASONIC_POLL_US        = 500_000
ULTRASONIC_THRESHOLD      = 5.0

AUTO_LOCK_DELAY        = 10.0
ULTRASONIC_REARM_DELAY = 10.0

DOOR_RELAY_PIN          = 17
DOOR_RELAY_PIN_2        = 27
DOOR_UNLOCK_DURATION    = 10.0
DOOR_MOTOR_RUN_DURATION = 1.9

WEB_HOST   = "127.0.0.1"
WEB_PORT   = 5000
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "your-secret-key-change-in-production-123!")
API_BASE_URL = "http://" + WEB_HOST + ":" + str(WEB_PORT) + "/api"

# Email Configuration
SMTP_USERNAME = "facialrecognitionandattendance@gmail.com"
SMTP_PASSWORD = "awky zocc uvnq qzrd"  # Google App Password
SMTP_SERVER   = "smtp.gmail.com"
SMTP_PORT     = 587
EMAIL_RECIPIENT = "suluv12@gmail.com"
UNKNOWN_FACE_EMAIL_THRESHOLD = 4
EMAIL_COOLDOWN = 60


LOG_DIR      = BASE_DIR / "logs"
LOG_FILE     = LOG_DIR / "system.log"
LOG_LEVEL    = "INFO"

ENROLLMENT_DIR    = BASE_DIR / "enrollments"
MAX_FACE_SAMPLES  = 5

PASSWORD_MIN_LENGTH  = 8
MAX_LOGIN_ATTEMPTS   = 5
LOCKOUT_DURATION     = 300
RATE_LIMIT_REQUESTS  = 10
RATE_LIMIT_WINDOW    = 60

THREAD_TIMEOUT         = 30
MAX_CONCURRENT_THREADS = 10

SENSOR_RETRY_ATTEMPTS    = 3
SENSOR_RETRY_DELAY       = 1
SENSOR_CONNECTION_TIMEOUT = 10

AUTH_RETRY_ATTEMPTS = 3
AUTH_RETRY_DELAY    = 2
CONFIDENCE_THRESHOLD = 0.6
AUTH_TIMEOUT        = 30

DOOR_STATE_CHECK_INTERVAL = 1
DOOR_EMERGENCY_TIMEOUT    = 60
DOOR_RETRY_ATTEMPTS       = 3

MAX_FRAME_HISTORY = 100
GC_THRESHOLD      = 100

GUI_UPDATE_INTERVAL = 50
GUI_WINDOW_WIDTH    = 1200
GUI_WINDOW_HEIGHT   = 800
